services:
  web:
    image: algiro/soulfoodcafe-report:0.0.1
    volumes:
      - soulFoodMovs:/home/soulFoodMovs
      - certs:/etc/letsencrypt/live/soulfoodcafe.es
    ports:
      - "8080"

  oauth2-proxy:
    ports:
      - "4180:4180"
    image: bitnami/oauth2-proxy:7.6.0
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_UPSTREAMS: "http://web:8080/"
      OAUTH2_PROXY_CLIENT_ID: <<client_id>>
      OAUTH2_PROXY_CLIENT_SECRET: <<client_secret>>
      OAUTH2_PROXY_COOKIE_SECRET: <<cookie_secret>>
      OAUTH2_PROXY_HTTPS_REDIRECT: "false"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_REDIRECT_URL: "http://soulfoodcafe.es:4180/oauth2/callback"
    restart: always
volumes:
  soulFoodMovs:
  certs:



