services:
  web:
    container_name: report-web
    image: algiro/soulfoodcafe-report:0.0.1
    volumes:
      - soulFoodMovs:/home/soulFoodMovs
      - certs:/etc/letsencrypt/live/soulfoodcafe.es
    ports:
      - "8080"
  app-gateway:
    container_name: nginx
    build:
      context: ./app-gateway
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
volumes:
  soulFoodMovs:
  certs:


